name: Publish

on:
  release:
    types: [released]

env:
  NODE_VERSION: 12
  WASM_PACK_VERSION: 0.12.1

jobs:
  publish-stremio-core-web:
    if: ${{ startsWith(github.ref, 'refs/tags/stremio-core-web') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          registry-url: https://registry.npmjs.org/
          cache-dependency-path: stremio-core-web/package-lock.json

      # For releasing we always use stable
      - name: Rust setup
        uses: dtolnay/rust-toolchain@1.77
        with:
          targets: wasm32-unknown-unknown
      - uses: taiki-e/install-action@v2
        with:
          tool: wasm-pack@${{ env.WASM_PACK_VERSION }}

      - name: Install NPM dependencies
        working-directory: stremio-core-web
        run: npm ci

      - name: Build
        working-directory: stremio-core-web
        run: npm run build

      - name: Publish to NPM
        working-directory: stremio-core-web
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: npm publish --access public
